/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['agent.js']) {
  _$jscoverage['agent.js'] = [];
  _$jscoverage['agent.js'][1] = 0;
  _$jscoverage['agent.js'][6] = 0;
  _$jscoverage['agent.js'][7] = 0;
  _$jscoverage['agent.js'][9] = 0;
  _$jscoverage['agent.js'][10] = 0;
  _$jscoverage['agent.js'][11] = 0;
  _$jscoverage['agent.js'][12] = 0;
  _$jscoverage['agent.js'][13] = 0;
  _$jscoverage['agent.js'][14] = 0;
  _$jscoverage['agent.js'][21] = 0;
  _$jscoverage['agent.js'][24] = 0;
}
_$jscoverage['agent.js'][1]++;
"use strict";
_$jscoverage['agent.js'][6]++;
var Actor = require("./actor");
_$jscoverage['agent.js'][7]++;
var id = require("./utils").id;
_$jscoverage['agent.js'][9]++;
var Agent = (function () {
  _$jscoverage['agent.js'][10]++;
  this._id = id();
  _$jscoverage['agent.js'][11]++;
  this._msgCount = 0;
  _$jscoverage['agent.js'][12]++;
  this._in = "_in_" + this._id;
  _$jscoverage['agent.js'][13]++;
  this._out = "_out_" + this._id;
  _$jscoverage['agent.js'][14]++;
  this._listeners = {};
});
_$jscoverage['agent.js'][21]++;
Agent.prototype = new Actor();
_$jscoverage['agent.js'][24]++;
exports = module.exports = Agent;
_$jscoverage['agent.js'].source = ["'use strict'","/**"," * Module dependencies."," */","","var Actor = require('./actor');","var id = require('./utils').id;","","var Agent = function () {","  this._id = id();  ","  this._msgCount = 0;","  this._in = '_in_' + this._id;","  this._out = '_out_' + this._id;","  this._listeners = {}; ","}","","/**"," * Inherits Actor."," */","","Agent.prototype = new Actor;","","","exports = module.exports = Agent;"];
