/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['agent.js']) {
  _$jscoverage['agent.js'] = [];
  _$jscoverage['agent.js'][5] = 0;
  _$jscoverage['agent.js'][6] = 0;
  _$jscoverage['agent.js'][9] = 0;
  _$jscoverage['agent.js'][10] = 0;
  _$jscoverage['agent.js'][11] = 0;
  _$jscoverage['agent.js'][12] = 0;
  _$jscoverage['agent.js'][13] = 0;
  _$jscoverage['agent.js'][14] = 0;
  _$jscoverage['agent.js'][21] = 0;
  _$jscoverage['agent.js'][24] = 0;
}
_$jscoverage['agent.js'][5]++;
var Actor = require("./actor");
_$jscoverage['agent.js'][6]++;
var uuid = require("node-uuid");
_$jscoverage['agent.js'][9]++;
var Agent = (function (name) {
  _$jscoverage['agent.js'][10]++;
  this.name = name.toString();
  _$jscoverage['agent.js'][11]++;
  this._id = this.name + uuid().slice(0, 4);
  _$jscoverage['agent.js'][12]++;
  this._msgCount = 0;
  _$jscoverage['agent.js'][13]++;
  this.hub = null;
  _$jscoverage['agent.js'][14]++;
  this._listeners = {};
});
_$jscoverage['agent.js'][21]++;
Agent.prototype = new Actor();
_$jscoverage['agent.js'][24]++;
exports = module.exports = Agent;
_$jscoverage['agent.js'].source = ["/**"," * Module dependencies."," */","","var Actor = require('./actor');","var uuid = require('node-uuid');","","","var Agent = function (name) {","  this.name = name.toString();","  this._id = this.name + uuid().slice(0,4);  ","  this._msgCount = 0;","  this.hub = null;","  this._listeners = {}; ","}","","/**"," * Inherits Actor."," */","","Agent.prototype = new Actor;","","","exports = module.exports = Agent;"];
