/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['interface.js']) {
  _$jscoverage['interface.js'] = [];
  _$jscoverage['interface.js'][1] = 0;
  _$jscoverage['interface.js'][6] = 0;
  _$jscoverage['interface.js'][7] = 0;
  _$jscoverage['interface.js'][9] = 0;
  _$jscoverage['interface.js'][10] = 0;
  _$jscoverage['interface.js'][11] = 0;
  _$jscoverage['interface.js'][12] = 0;
  _$jscoverage['interface.js'][13] = 0;
  _$jscoverage['interface.js'][14] = 0;
  _$jscoverage['interface.js'][21] = 0;
  _$jscoverage['interface.js'][23] = 0;
}
_$jscoverage['interface.js'][1]++;
"use strict";
_$jscoverage['interface.js'][6]++;
var Actor = require("./actor");
_$jscoverage['interface.js'][7]++;
var id = require("./utils").id;
_$jscoverage['interface.js'][9]++;
var Interface = (function () {
  _$jscoverage['interface.js'][10]++;
  this._id = id();
  _$jscoverage['interface.js'][11]++;
  this._msgCount = 0;
  _$jscoverage['interface.js'][12]++;
  this._in = "_in_" + this._id;
  _$jscoverage['interface.js'][13]++;
  this._out = "_out_" + this._id;
  _$jscoverage['interface.js'][14]++;
  this._listeners = {};
});
_$jscoverage['interface.js'][21]++;
Interface.prototype = new Actor();
_$jscoverage['interface.js'][23]++;
exports = module.exports = Interface;
_$jscoverage['interface.js'].source = ["'use strict'","/**"," * Module dependencies."," */","","var Actor = require('./actor');","var id = require('./utils').id;","","var Interface = function ()  {","  this._id = id();  ","  this._msgCount = 0;","  this._in = '_in_' + this._id;","  this._out = '_out_' + this._id;","  this._listeners = {}; ","}","","/**"," * Inherits Actor."," */","","Interface.prototype = new Actor;","","exports = module.exports = Interface;"];
