/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['utils.js']) {
  _$jscoverage['utils.js'] = [];
  _$jscoverage['utils.js'][5] = 0;
  _$jscoverage['utils.js'][17] = 0;
  _$jscoverage['utils.js'][18] = 0;
  _$jscoverage['utils.js'][19] = 0;
  _$jscoverage['utils.js'][20] = 0;
  _$jscoverage['utils.js'][21] = 0;
  _$jscoverage['utils.js'][23] = 0;
  _$jscoverage['utils.js'][24] = 0;
  _$jscoverage['utils.js'][25] = 0;
}
_$jscoverage['utils.js'][5]++;
var _ = require("../underscore");
_$jscoverage['utils.js'][17]++;
this.createMessage = (function (channel, body, options) {
  _$jscoverage['utils.js'][18]++;
  msg = {};
  _$jscoverage['utils.js'][19]++;
  msg.answerMe = false;
  _$jscoverage['utils.js'][20]++;
  msg.ttl = 1000;
  _$jscoverage['utils.js'][21]++;
  msg = _.extend(msg, options);
  _$jscoverage['utils.js'][23]++;
  msg.channel = channel;
  _$jscoverage['utils.js'][24]++;
  msg.body = body;
  _$jscoverage['utils.js'][25]++;
  return msg;
});
_$jscoverage['utils.js'].source = ["/**"," * Module dependencies."," */","","var _ = require('../underscore');","","/**"," * Constructs messages"," * "," * @param {string} [channel] the channel"," * @param {any} [body] message body"," * @param {object} [options] options"," * @returns {object} message "," */","","","this.createMessage = function (channel, body, options) {","  msg = {};","  msg.answerMe = false; ","  msg.ttl = 1000;","  msg = _.extend(msg, options);","  // Do not set this manually","  msg.channel = channel;","  msg.body = body;","  return msg;","}"];
